image: node:6.9.4

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1

#  install node js
  - apt-get --quiet install -y build-essential
  - curl -sL http://deb.nodesource.com/setup_6.x | bash -
  - apt-get --quiet install -y nodejs
  - apt-get --quiet update --yes
  - npm -v
  - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - apt-get -y update && apt-get install -y google-chrome-stable

stages:
  - test

#deploy debug
test:
  stage: test
  script:
    - npm install
    - npm run test:ci